title: Talha Arshad # your name (or website title) here
logo: "/images/profile_new_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong><font size="+1">Machine learning for advanced manufacturing</font></strong>
  <br><br>
  <a href="https://www.linkedin.com/in/tarshad/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-50N1D6RK7Z  # UA-000000-0  # your Google Analytics tracking ID here
